-- budget definition
DROP TABLE "budgetItem";

DROP TABLE "payday";

DROP TABLE "budget";

drop TABLE "payee";

DROP TABLE "income";

CREATE TABLE "budget" (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	budgetDate DATE NOT NULL,
	CONSTRAINT UNIQUE_BUDGET UNIQUE ( budgetDate )
);

-- income definition


CREATE TABLE "income" (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY key,
	name varchar(100) NOT NULL,
	budgetedPay NUMERIC, 
	payFrequency varchar(100), 
	nextPayDate DATE);
	
-- payee definition

CREATE TABLE "payee" (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY key,
	name varchar(100) NOT NULL,
	url varchar(1000),
	username varchar(100),
	password varchar(100), 
	budgetedPayment NUMERIC, 
	due_on INTEGER, 
	balance NUMERIC, 
    income_id int,
	constraint payee_income_FK foreign key ( income_id ) references "income" (id)
   );
   
-- payday definition


CREATE TABLE "payday" (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY key,
	budget_id int not null,
	income_id int not null, 
	payDate DATE, amount float,
	constraint PAYDAY_INCOME_FK foreign key ( income_id ) references "income",
	constraint PAYDAY_BUDGET_FK foreign key ( budget_id ) references "budget"
);  

-- budgetItem definition



CREATE TABLE "budgetItem" (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY key,
	payday_id int not null,
	payee_id int not null, 
	amount float,
	payed boolean,
	payDate DATE, 
	constraint BUDGETITEM_PAYDAY_FK foreign key ( payday_id ) references "payday",
	constraint BUDGETITEM_PAYEE_FK foreign key ( payee_id ) references "payee"
);