/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.homebudget;

/*
 * Copyright (C) 2024 Gerry Hobbs
 * bassnfool2@gmail.com
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */


import java.io.IOException;

import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.image.Image;


public class HomeBudgetInit extends Application {
	@Override
	public void start(Stage primaryStage) {
		try {
			HomeBudgetController homeBudgetController = new HomeBudgetController();
			
			Scene homeBudgetScene = new Scene(homeBudgetController);
			primaryStage.setTitle("HomeBudget");
			primaryStage.getIcons().add(new Image(HomeBudgetController.class.getResourceAsStream("icons/HB.png")));
			primaryStage.setScene(homeBudgetScene);			
			primaryStage.setMaximized(true);
			loadConfig(homeBudgetController);
			primaryStage.show();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	private void loadConfig(HomeBudgetController homeBudgetController) {
		homeBudgetController.initOpenRecent();
		if ( Settings.config != null && Settings.config.getProperty("recent.files") != null && !Settings.config.getProperty("recent.files").trim().equals("")) {
			String[] recentFiles = Settings.config.getProperty("recent.files").split(",");
			homeBudgetController.setRecentFiles(recentFiles);
			HomeBudgetController.setHomeBudgetDb(recentFiles[0]);
		} else {
			homeBudgetController.openFile();
		}

	}

	public static void main(String[] args) {
		try {
			Settings.loadProperties();
		} catch (IOException e) {
			e.printStackTrace();
		}
		String type = "derby";
		if ( args.length > 0) {
			type = args[0];
		}
		HomeBudgetController.setDBType(type);
		launch(args);
	}
}
